# Use a base image with Python installed
FROM python:3.8-slim

# Install PostgreSQL client for pg_isready and psycopg2 dependencies
RUN apt-get update && apt-get install -y postgresql-client libpq-dev gcc && rm -rf /var/lib/apt/lists/*

# Install psycopg2
RUN pip install psycopg2

# Set working directory
WORKDIR /app

# Copy the Python script and CSV data into the container
COPY load_data.py /app/load_data.py
COPY data/books.csv /app/books.csv

